services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest@sha256:1dd281365d61fb76fd4474ba67e36ec94d2e8dbc67a8032ba10731c01701c97e
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - TMPDIR=/transcode
    volumes:
      - /docker/appdata/plex:/config
      - /mnt/storage/data/media/movies:/movies
      - /mnt/storage/data/media/series:/tv
    tmpfs:
      - /transcode:size=4g,mode=1777

  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest@sha256:cb2226d9ab37f084d67a396e3c79059ca7d0fa7e1b2e6f1a473472af2afa7b12
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/tautulli:/config
    ports:
      - 8181:8181

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/overseerr:/app/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest@sha256:49b96245cc456e07628009dc0d28827679e0e94b30eadcd1ab7d59feaede8a42
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/storage/data:/data
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest@sha256:4705417494fbd9b74b917477dcb467911365c7d153be4e3f794ac9db728bee49
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TZ}
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/storage/data:/data
    ports:
      - 8989:8989

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest@sha256:b59c52b873304de1acb24006062227d2b37694d4bb161791f2daf7da1f01ac75
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/bazarr:/config
      - /mnt/storage/data/media:/data/media
    ports:
      - 6767:6767

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:a68c4cfb7b07c39cf3f13e7f1d23d333c1e4a60304d37bc1eec7af3eacfe12d5
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8088
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /mnt/storage/data/torrents:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop@sha256:aeb303a86be70dfb3fa5508bbd9399f5123b74f73b00b91eb76eb34efe4c5650
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/prowlarr:/config
    ports:
      - 9696:9696

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
