services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:0df89c904da71e94a0c9ed3c89a890f01488321b5f10ac1e0c0bedcead9af6e4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.home.lan`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

  wud:
    container_name: wud
    image: getwud/wud:latest@sha256:2df7cafa0fc84cdd66ad976163abc5390fa5995e0b5788a90e6a5303706bc21a
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WUD_WATCHER_LOCAL_CRON=0 */6 * * *
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/appdata/wud:/store
    ports:
      - 3001:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.wud.rule=Host(`wud.home.lan`)
      - traefik.http.routers.wud.entrypoints=websecure
      - traefik.http.routers.wud.tls=true
      - traefik.http.services.wud.loadbalancer.server.port=3000

  beszel:
    container_name: beszel
    image: henrygd/beszel:latest@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - /docker/appdata/beszel:/beszel_data
    ports:
      - 8090:8090
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.home.lan`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.services.beszel.loadbalancer.server.port=8090

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - LISTEN=45876
      - KEY=${BESZEL_HUB_KEY:-}
    volumes:
      - /docker/appdata/beszel-agent:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1@sha256:3d632903e6af34139a37f18055c4f1bfd9b7205ae1138f1e5e8940ddc1d176f9
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - /docker/appdata/uptime-kuma:/app/data
    ports:
      - 3011:3001
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`kuma.home.lan`)
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.tls=true
      - traefik.http.services.kuma.loadbalancer.server.port=3001
