### MONITORING
services:
  glances:
    container_name: glances
    image: nicolargo/glances:ubuntu-latest-full@sha256:e17096f1ba0407d0589bec7976ba6ac2f1b6fea886bb090d59090c9244930eae
    restart: unless-stopped
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
    environment:
      - "GLANCES_OPT=-w"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 61208-61209:61208-61209

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:0df89c904da71e94a0c9ed3c89a890f01488321b5f10ac1e0c0bedcead9af6e4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  wud:
    container_name: wud
    image: getwud/wud:latest@sha256:2df7cafa0fc84cdd66ad976163abc5390fa5995e0b5788a90e6a5303706bc21a
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WUD_WATCHER_LOCAL_CRON=0 */6 * * *
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/appdata/wud:/store
    ports:
      - 3001:3000

### DASHBOARD
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest@sha256:234aa35d4abb76ca6c41845218a633e7af21ad14bbe3e292c8e251abf5d5b3fb
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/heimdall:/config
    ports:
      - 80:80
      - 443:443

### MEDIA
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest@sha256:1dd281365d61fb76fd4474ba67e36ec94d2e8dbc67a8032ba10731c01701c97e
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /docker/appdata/plex:/config
      - /mnt/storage/data/media/movies:/movies
      - /mnt/storage/data/media/series:/tv

  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest@sha256:cb2226d9ab37f084d67a396e3c79059ca7d0fa7e1b2e6f1a473472af2afa7b12
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/tautulli:/config
    ports:
      - 8181:8181

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/overseerr:/app/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest@sha256:49b96245cc456e07628009dc0d28827679e0e94b30eadcd1ab7d59feaede8a42
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/storage/data:/data
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest@sha256:4705417494fbd9b74b917477dcb467911365c7d153be4e3f794ac9db728bee49
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TZ}
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/storage/data:/data
    ports:
      - 8989:8989

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest@sha256:b59c52b873304de1acb24006062227d2b37694d4bb161791f2daf7da1f01ac75
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/bazarr:/config
      - /mnt/storage/data/media:/data/media
    ports:
      - 6767:6767

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:a68c4cfb7b07c39cf3f13e7f1d23d333c1e4a60304d37bc1eec7af3eacfe12d5
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8088
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /mnt/storage/data/torrents:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop@sha256:aeb303a86be70dfb3fa5508bbd9399f5123b74f73b00b91eb76eb34efe4c5650
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/prowlarr:/config
    ports:
      - 9696:9696

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"

### HOME AUTOMATION
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:75ef6851d2e48d366764cdb6b569b7ad8be77dcc8e0d1b9aa508ac90e42d4c58
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /docker/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      DISABLE_JEMALLOC: 1
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest@sha256:077fe4ff4c49df1e860c98335c77dda08360629e0e2a718147027e4db3eace9d
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/appdata/mosquitto:/mosquitto/config/
      - /docker/appdata/mosquitto/data:/mosquitto/data
      - /docker/appdata/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:latest@sha256:163e7351430a95d550d5b1bb958527edc1eff115eb013ca627f3545a192e853f
    restart: unless-stopped
    network_mode: host
    privileged: true
    depends_on:
      - mosquitto
    volumes:
      - /docker/appdata/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=${TZ}

### NETWORK
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8068:68/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
      - "8443:443/udp"
      - "3000:3000/tcp"
    volumes:
      - /docker/appdata/adguard-config:/opt/adguardhome/conf
      - /docker/appdata/adguard-work:/opt/adguardhome/work

### VOLUMES
volumes:
  adguard-config:
    name: adguard-config
    driver: local
  adguard-work:
    name: adguard-work
    driver: local
